### ISSUE TITLE
Support for UK and EU Marketplaces

### ISSUE THREAD

**Issue by amistry007** [aludvigsson/sqp-fetcher#1]
Is it possible to add support for UK and EU marketplaces?

**Comment by amistry007** [comment]
@aludvigsson is this now implemented? I did see some commits around this but was not sure if fully implemented yet.

**Comment by aludvigsson** [comment]
it is, but it seems bugged, let me research it tomorrow @amistry007

**Comment by amistry007** [comment]
Any update on this issue?

**Comment by amistry007** [comment]
Hey @aludvigsson merry Christmas! Just wondering if there is any update on this?

**Comment by amistry007** [comment]
Hey @aludvigsson ...do you think you could look at this soon?

**Comment by aludvigsson** [comment]
@amistry007 sorry! been a bit busy with family life + work but let me check this today, i will push later :)

**Comment by aludvigsson** [comment]
@amistry007 hey - just tried UK/DE on my end, seems to be OK now. Could you try the latest commited version?

**Comment by amistry007** [comment]
@aludvigsson - perfect! Seems to be working. One request...could you add the ASIN into the downloaded CSV as a column as when you download multiple ASINS its hard to easily tie back the search queries to the correct ASIN.

**Comment by amistry007** [comment]
@aludvigsson - scratch the request to update the CSV...I've done this, tested it and submitted a pull request.
