### ISSUE TITLE
Manifest Permission Issue

### ISSUE THREAD

**Issue by amistry007** [aludvigsson/sqp-fetcher#2]
I see manifest error "Permission 'http://*/*' is unknown or URL pattern is malformed." when I installed it. How do I fix this?

**Comment by kmander** [comment]
![Screenshot 2023-11-07 at 13 58 47](https://github.com/aludvigsson/sqp-fetcher/assets/1092245/4b247088-8543-4638-baeb-0a035e75e226)

Also seeing Chrome kick out some validation issues with the manifest. Also not finding the extension is functioning (no data is extracted).

But massive kudos for trying to tackle this well needed feature!

**Comment by aludvigsson** [comment]
Hey! Ill add some updates tmrw that will hopefully fix this and your EU request :)

**Comment by aludvigsson** [comment]
This should be fixed now :)

**Comment by kmander** [comment]
Yep! It's working well.

We've working on a whole app for SQPR data (that also brings in BA, PPC, organic, etc data as well).

![399868502_10101512997699326_8893968894148832134_n](https://github.com/aludvigsson/sqp-fetcher/assets/1092245/bc7e619d-9a0b-4be4-a175-f2caf584c95a)

It also uses a Chrome extension to extract the data – but in a different fashion (cronjob-style repeating background task).

Not a coder myself, but have a dev in the team. Happy to geek out on SQPR data anytime tho. Super interesting, especially when blended in with other data + time-series trends.

**Comment by amistry007** [comment]
Perfect @aludvigsson  - working for me too now! Any idea when we can also expect the fix for EU data  Issue#1?

**Comment by amistry007** [comment]
@kmander your platform looks interesting...do you also pull in organic rank data too? Any demo account I can check it out with?

I think I have found my people @kmander and @aludvigsson would love to join in any conversations you have in regards to this data! I used to be a developer in my past life and creating this plugin was on my todo list too but @aludvigsson you beat me to it!

**Comment by aludvigsson** [comment]
@kmander great job, your extension is what inspired to me to this one :) EU should probably be done tomorrow

**Comment by kmander** [comment]
@amistry007 Yep, you can sign up freely on https://datasmash.co/ – we're still figuring out the actual focus/USPs of the app before we turn on payments. We don't yet pull organic rank data, actually, but have it on the roadmap. Getting accurate data is actually quite a challenge as it usually requires residential IPs which is very expensive.

@aludvigsson appreciated :) Are you an active seller yourself? Or working on building saas apps?

**Comment by aludvigsson** [comment]
@kmander a mixture of both, not really building anything just making my own amz life easier :)

**Comment by amistry007** [comment]
@aludvigsson - I can relate to that I am in exact same boat. Is there anything else you built thats useful?

**Comment by kmander** [comment]
@amistry007 Have built a ton of internal tools to handle customer service, inventory management, and so on. The ethos was to be able to grow without added complexity. But honestly, I went totally overkill with it and the actual product business suffered from a dilution of focus. There's definitely opportunities to spin out the software you've built to then be a SaaS app for other Amazon sellers. But the challenge is that the fringe use cases from users can result in feature creep. We've built our own PPC app and have a unique take on it. But it's daunting to take that to market!

**Comment by amistry007** [comment]
@kmander - what you say resonates very closely with me...I too sometimes have built internal tools which distracted me away from focussing on the core business...but being ex-developer I love coding and working out automated solutions to problems we are having in the business...but as you say we can get carried away with it!

Would love to chat more about your PPC app!

**Comment by kmander** [comment]
Happy to jump on a call sometime: https://tidycal.com/kmander
Or email: keith@yuca.co
