### ISSUE TITLE
Custom Filename

### ISSUE THREAD

**Issue by amistry007** [aludvigsson/sqp-fetcher#3]
The downloaded filename is called data.csv...can we rename this to ASIN-WKXX-WKYY.CSV where XX is the week of start date and YY is week of end date? Or at least include startDate and endDate along with ASIN in the filename?

**Comment by aludvigsson** [comment]
sure, ill fix this asap :)

**Comment by aludvigsson** [comment]
@amistry007 latest commit has startdate-enddate-asin as new filenames structure :)

**Comment by amistry007** [comment]
Perfect!
