### ISSUE TITLE
Multiple files all with SQP data for every ASIN requested

### ISSUE THREAD

**Issue by amistry007** [aludvigsson/sqp-fetcher#6]
Seems that when you enter multiple ASINs it creates multiple files with data for all ASINs contained in each file.

I actually don't mind all ASINs in one file as I just downloaded one years worth of data for all of my ASINs and it put into one file which was quite convenient for analysis...but it just created duplicates of the file named with each ASIN.

Maybe a toggle switch on the UI to say store in one file or separate into multiple files per ASIN.

Not an urgent issue...just a feature request I guess...most important just to get rid of the duplicate files as thats probably quite inefficient.

**Comment by aludvigsson** [comment]
ah, let me check this @amistry007 - so all ASINs data gets in the each file?

**Comment by amistry007** [comment]
Yup exactly

**Comment by amistry007** [comment]
I've fixed this issue in the latest pulll request. But there still seems to be some intermittent failure with response code 429 which I cant figure out why is happening. So, on occasions when fetch is pressed and data returned and then fetch is pressed again it fails. Also added toggle for one CSV file...but not implemented that yet.

**Comment by amistry007** [comment]
closing this issue and raise more appropriate ones.
